title: "Di Liu"
email: "youremail@example.com"
description: "Postdoctoral Researcher at IMPA, Brazil"
baseurl: ""
url: "https://your-username.github.io"

remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

author:
  name: "Di Liu"
  avatar: "/assets/images/profile.jpg"
  bio: "Postdoctoral Researcher at IMPA. Research in Optimization, Monotone Operators, Circumcenter Methods."
  location: "Rio de Janeiro, Brazil"
  links:
    - label: "Google Scholar"
      url: "https://scholar.google.com/"
    - label: "GitHub"
      url: "https://github.com/your-username"
    - label: "Email"
      url: "mailto:youremail@example.com"
